import type { Metadata } from "next";
import { SettingsProvider } from "@/context/SettingsContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { PatientProvider } from "@/context/PatientContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SettingsProvider>
            <PatientProvider>
              {children}
            </PatientProvider>
          </SettingsProvider>
         </AuthProvider>
      </body>
    </html>
  );
}
